services:

  ima-redis:
      image: redis/redis-stack:latest
      container_name: intelligent-mfg-assistant-Redis
      ports:
        - "6379:6379"
        - "8001:8001"
      environment:
        REDIS_ARGS: "--appendonly yes"
      volumes:
        - ima-redis-data:/data
      healthcheck:
        test: ["CMD", "Redis-cli", "ping"]
        interval: 5s
        timeout: 3s
        retries: 10

volumes:
  ima-redis-data: